contact:
  email: powen@renci.org
  name: Phil Owen
  x-id: https://github.com/phillipsowen
  x-role: responsible developer
description: ''
servers:
- description: Default server
  url: https://TBD
termsOfService: http://robokop.renci.org:7055/tos?service_long=APSVIZ&provider_long=RENCI
title: APSVIZ Settings
