# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

name: Create and publish the APSVIZ Supervisor settings Docker image tagged with "latest" and version number

# trigger event is publishing a release in the repo
on:
  release:
    types: [published]

# working parameters that are specific to this script
env:
  REGISTRY: containers.renci.org/eds/apsviz-settings

# job definition
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # job steps
    steps:
      - uses: actions/checkout@v1

      # loging into the renci image registry
      - name: Login to containers.renci.org
        uses: docker/login-action@v2
        with:
          registry: containers.renci.org
          username: ${{ secrets.USER }}
          password: ${{ secrets.PW }}

      # get python installed
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13

      # get the tag for the image
      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # build and push the image. The docker v3 action automatically handles the git checkout.
      - name: Build/Push the image to the registry
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: |
            ${{ env.REGISTRY }}:latest
            ${{ env.REGISTRY }}:${{ steps.get_version.outputs.VERSION }}

    linting:
        name: PyLint
        runs-on: ubuntu-latest
        needs: install
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-python@v2
          - run: pip3 install -U pip setuptools
          - run: pip3 install -U -r requirements.txt
          - run: pylint --msg-template={path}:{line}:{column}:{C}:({symbol}){msg} --rcfile=.pylintrc --recursive=y ./
