# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

name: Create and publish the APSVIZ Supervisor settings Docker image tagged with "latest" and version number

# trigger event is publishing a release in the repo
on:
  release:
    types: [published]

# working parameters that are specific to this script
env:
  REGISTRY: containers.renci.org/eds/apsviz-settings

# job definition
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # job steps
    steps:
      - name: Login to containers.renci.org
        uses: docker/login-action@v2
        with:
          registry: containers.renci.org
          username: ${{ secrets.USER }}
          password: ${{ secrets.PW }}
      
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.13      
      
      - name: Chackout code
        uses: actions/checkout@v1
        
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          
      - name: Run Pylint
        run: |
          python lint.py --msg-template=".\{path}:{line}:{column}:{C}:({symbol}){msg}" --rcfile=.pylintrc --recursive=y ./
        
      # get the tag for the image        
      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # build and push the image. The docker v3 action automatically handles the git checkout.
      - name: Build/Push the image to the registry
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: |
            ${{ env.REGISTRY }}:latest
            ${{ env.REGISTRY }}:${{ steps.get_version.outputs.VERSION }}
